[info]
maintainer = "TeaClientMC"
desc = "The largest Minecraft server in the world, with a huge variety of games and minigames to play!"
server_address = "mc.hypixel.net"

# This is images specified in /images dir it is based on sha256
[base64_png]
icon = "b600678e-298a-4da2-b07d-507dbde0cf2b"
banner = "b05f3099-fdc3-4ffc-af4e-cbb88b429219"

[socials]
homepage = "https://hypixel.net"
store = "https://store.hypixel.net"
discord = "https://discord.gg/hypixel"
twitter = "https://twitter.com/HypixelNetwork"
youtube = "https://www.youtube.com/Hypixel"
tiktok = "https://www.tiktok.com/@hypixel"
twitch = "https://www.twitch.tv/hypixel"
